
print_freq: 100
output_dir: './logs'
checkpoint_freq: 10


sync_bn: True
find_unused_parameters: False


use_amp: True
scaler:
  type: GradScaler
  enabled: True


use_ema: False
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000
